# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etablissements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annee_specialite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Annee_specialite',
                'verbose_name_plural': 'Annees_specialite',
                'db_table': 'annee_specialite',
            },
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=256)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etablissements.Departement')),
            ],
            options={
                'verbose_name': 'Cycle',
                'verbose_name_plural': 'Cycles',
                'db_table': 'cycle',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=256)),
                ('coefficient', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'db_table': 'module',
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=256)),
                ('annee_specialite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semestres_annee_specialite', to='modules.Annee_specialite')),
            ],
            options={
                'verbose_name': 'Semestre',
                'verbose_name_plural': 'Semestres',
                'db_table': 'semestre',
            },
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=256)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.Cycle')),
            ],
            options={
                'verbose_name': 'Specialite',
                'verbose_name_plural': 'Specialites',
                'db_table': 'specialite',
            },
        ),
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=256)),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unites_semestre', to='modules.Semestre')),
            ],
            options={
                'verbose_name': 'Unite',
                'verbose_name_plural': 'Unites',
                'db_table': 'unite',
            },
        ),
        migrations.AddField(
            model_name='module',
            name='unite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules_unite', to='modules.Unite'),
        ),
        migrations.AddField(
            model_name='annee_specialite',
            name='specialite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.Specialite'),
        ),
    ]
