# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enseignants', '0001_initial'),
        ('etablissements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=256)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cycle',
                'verbose_name_plural': 'Cycles',
                'db_table': 'cycle',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=256)),
                ('coefficient', models.IntegerField(default=2)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignants', to='enseignants.Enseignant')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'db_table': 'module',
            },
        ),
        migrations.CreateModel(
            name='Parcours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=256)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responsable_parcours', to='enseignants.Enseignant')),
            ],
            options={
                'verbose_name': 'Parcours',
                'verbose_name_plural': 'Parcours',
                'db_table': 'parcours',
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=256)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('parcours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semestres', to='modules.Parcours')),
            ],
            options={
                'verbose_name': 'Semestre',
                'verbose_name_plural': 'Semestres',
                'db_table': 'semestre',
            },
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=256)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialites', to='modules.Cycle')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialites', to='etablissements.Departement')),
                ('responsable', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responsable_specialite', to='enseignants.Enseignant')),
            ],
            options={
                'verbose_name': 'Specialite',
                'verbose_name_plural': 'Specialites',
                'db_table': 'specialite',
            },
        ),
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=256)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unites', to='modules.Semestre')),
            ],
            options={
                'verbose_name': 'Unite',
                'verbose_name_plural': 'Unites',
                'db_table': 'unite',
            },
        ),
        migrations.AddField(
            model_name='parcours',
            name='specialite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcours', to='modules.Specialite'),
        ),
        migrations.AddField(
            model_name='module',
            name='unite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='modules.Unite'),
        ),
    ]
