# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 03:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annee_specialite',
            name='specialite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annees_specialite', to='modules.Specialite'),
        ),
        migrations.AlterField(
            model_name='specialite',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialites', to='modules.Cycle'),
        ),
    ]
