# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 23:18
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modules', '0001_initial'),
        ('etablissements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('numero', models.CharField(max_length=100)),
                ('note', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('mention', models.CharField(choices=[('sans mention', 'Bac sans mention : entre 10 et 12/20'), ('mention assez bien', 'Bac avec mention assez bien : entre 12 et 14/20'), ('mention bien', 'Bac avec mention bien : entre 14 et 16/20'), ('mention très bien', 'Bac avec mention très bien : 16/20 et plus')], max_length=100)),
                ('session', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], default=2018)),
            ],
            options={
                'verbose_name': 'Bac',
                'verbose_name_plural': 'Bacs',
                'db_table': 'etudiant_bac',
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexe', models.CharField(blank=True, choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=100)),
                ('adresse', models.CharField(max_length=256)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=256, null=True)),
                ('nationalite', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('telephone', models.CharField(blank=True, max_length=256)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Etudiant',
                'verbose_name_plural': 'Etudiants',
                'db_table': 'etudiant',
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.CharField(blank=True, choices=[('Inscription', 'Inscription'), ('Reinscription', 'Reinscription')], max_length=100)),
                ('annee_specialite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.Annee_specialite')),
                ('annee_universitaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etablissements.Annee_universitaire')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscriptions.Etudiant')),
            ],
            options={
                'verbose_name': 'inscription',
                'verbose_name_plural': 'inscriptions',
                'db_table': 'etudiant_inscription',
            },
        ),
        migrations.AddField(
            model_name='bac',
            name='etudiant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inscriptions.Etudiant'),
        ),
    ]
