# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 02:14
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etablissements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=256)),
                ('note', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('mention', models.CharField(choices=[('sans mention', 'Bac sans mention : entre 10 et 12/20'), ('mention assez bien', 'Bac avec mention assez bien : entre 12 et 14/20'), ('mention bien', 'Bac avec mention bien : entre 14 et 16/20'), ('mention très bien', 'Bac avec mention très bien : 16/20 et plus')], max_length=256)),
                ('session', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], default=2018)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bac',
                'verbose_name_plural': 'Bacs',
                'db_table': 'bac',
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=256)),
                ('prenom', models.CharField(max_length=256)),
                ('sexe', models.CharField(blank=True, choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=256)),
                ('adresse', models.CharField(max_length=256)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=256, null=True)),
                ('nationalite', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('telephone', models.CharField(blank=True, max_length=256)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etudiant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Etudiant',
                'verbose_name_plural': 'Etudiants',
                'db_table': 'etudiant',
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.CharField(blank=True, choices=[('Inscription', 'Inscription'), ('Reinscription', 'Reinscription')], max_length=100)),
                ('annee_universitaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='etablissements.Annee_universitaire')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='inscriptions.Etudiant')),
                ('parcours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='modules.Parcours')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'db_table': 'inscription',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(blank=True, choices=[('CC', 'CC'), ('EF', 'EF'), ('ER', 'ER')], max_length=256)),
                ('note', models.FloatField()),
                ('inscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='inscriptions.Inscription')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='modules.Module')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'db_table': 'note',
            },
        ),
        migrations.AddField(
            model_name='bac',
            name='etudiant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bac', to='inscriptions.Etudiant'),
        ),
    ]
