# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 23:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0002_inscription_date_inscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscription',
            old_name='specialite',
            new_name='annee_specialite',
        ),
    ]
