# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0002_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='inscription',
        ),
        migrations.AddField(
            model_name='note',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
