# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 05:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0002_auto_20180602_0445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Groupe',
                'verbose_name_plural': 'Groupes',
                'db_table': 'groupe',
            },
        ),
        migrations.AddField(
            model_name='inscription',
            name='groupe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='inscriptions.Groupe'),
        ),
    ]
