# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 03:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0003_auto_20180530_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='inscriptions.Etudiant'),
        ),
    ]
