# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0003_auto_20180602_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
