# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 17:41
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0004_auto_20180525_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='nationalite',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
