# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 03:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0004_auto_20180530_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='annee_universitaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_annee_universitaire', to='etablissements.Annee_universitaire'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_etudiant', to='inscriptions.Etudiant'),
        ),
        migrations.AlterField(
            model_name='note',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_etudiant', to='inscriptions.Etudiant'),
        ),
        migrations.AlterField(
            model_name='note',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_module', to='modules.Module'),
        ),
    ]
