# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-09 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0004_note_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='moyenne1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='moyenne2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='noteCC',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='noteEF',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='noteER',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
