# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-09 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0005_auto_20180609_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='note',
        ),
    ]
