# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0001_initial'),
        ('inscriptions', '0005_auto_20180530_0444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='date',
        ),
        migrations.AddField(
            model_name='note',
            name='annee_universitaire',
            field=models.ForeignKey(default=0.9995044598612488, on_delete=django.db.models.deletion.CASCADE, related_name='notes_annee_universitaire', to='etablissements.Annee_universitaire'),
            preserve_default=False,
        ),
    ]
