# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 02:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0006_auto_20180530_0447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='etudiant',
        ),
        migrations.AddField(
            model_name='note',
            name='inscription_etudiant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes_inscription_etudiant', to='inscriptions.Inscription'),
        ),
        migrations.AlterModelTable(
            name='note',
            table='inscription_etudiant_module_note',
        ),
    ]
