# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0008_bac'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bac',
            options={'verbose_name': 'Bac', 'verbose_name_plural': 'Bacs'},
        ),
        migrations.AlterModelTable(
            name='bac',
            table='etudiant_bac',
        ),
    ]
