# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 23:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0009_auto_20180526_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='bac',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inscription',
            name='date_inscription',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
