# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 03:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annee_universitaire',
            options={'verbose_name': 'Annee universitaire', 'verbose_name_plural': 'Annees universitaire'},
        ),
        migrations.AlterField(
            model_name='departement',
            name='chef',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chaf_departement', to='enseignants.Enseignant'),
        ),
        migrations.AlterField(
            model_name='departement',
            name='domaine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departements', to='etablissements.Domaine'),
        ),
    ]
