# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-08 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='open',
            field=models.BooleanField(default=False),
        ),
    ]
