# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 02:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=256)),
                ('prenom', models.CharField(max_length=256)),
                ('sexe', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=256)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=256, null=True)),
                ('grade', models.CharField(choices=[('PR', 'Professeur'), ('MCA', 'Maitre de conference A'), ('MCB', 'Maitre de conference B'), ('MAA', 'Maitre assistant A'), ('MAB', 'Maitre assistant B')], max_length=256)),
                ('nationalite', django_countries.fields.CountryField(max_length=2)),
                ('adresse', models.CharField(max_length=256)),
                ('telephone', models.CharField(max_length=256)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enseignant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
                'db_table': 'enseignant',
            },
        ),
    ]
